### ISSUE TITLE
code?

### ISSUE THREAD

**Issue by nigelhenry** [zhiqic/ChartReader#1]
Hi. has the repo been moved? Will it be re-posted?

**Comment by zhiqic** [comment]
We have recently made the decision to move our previously public code repository. The reason for this is that our paper is currently under review, and we plan to reopen the repository once the paper is accepted. However, there are still some property rights issues that need to be addressed regarding the code dependencies used in the previous repository, which I am currently working on resolving.

**Comment by zhiqic** [comment]
Due to intellectual property and project constraints, we are unable to release the pre-trained model. However, we have made available the associated dataset and code for your reference.
